# Конфигурация для обучения всех 5 учителей на FashionMNIST
dataset: FashionMNIST
epochs: 30
batch_size: 128
lr: 0.001
save_dir: ./pretrained
teachers:
  - teacher_cnn1
  - teacher_cnn2
  - teacher_resnet
  - teacher_vgg
  - teacher_densenet

